### ISSUE TITLE
Cannot start on Matlab R2018a and Matlab R2020a

### ISSUE THREAD

**Issue by tommschowar** [himynameisfuego/SiTraNo#1]
### Review questions
I am one of the reviewers for your submission to DaFX20.
Unfortunately I cannot start your app in Matlab in R2018a and R2020a (other versions I do not have installed).
The *Image Processing Toolbox* and the *Audio Toolbox* are both installed.
Maybe I installed your app wrongly or did something else wrong.
Please help me with this issue asap.

The corresponding error messages are
### R2018a
```
Error using SiTraNo0x2D1App/startApp (line 90)
Error defining property 'GridLayout' of class 'SiTraNo':
Class named 'matlab.ui.container.GridLayout' is undefined or does not support property validation.
Error in SiTraNo0x2D1App (line 48)
            startApp(obj)
Error in appinstall.internal.runapp>execute (line 86)
out = evalin('caller', [script ';']);
Error in appinstall.internal.runapp>runapp13a (line 65)
outobj = execute(fullfile(appinstalldir, [wrapperfile 'App.m']));
Error in appinstall.internal.runapp>runcorrectversion (line 44)
    appobj = runapp13a(appinstalldir);
Error in appinstall.internal.runapp (line 19)
            runcorrectversion(appmetadata, appentrypoint, addonmetadatadir); 
```

### R2020a
```
Functionality not supported with figures created with the uifigure function. For more information, see Graphics Support in App Designer.

Error in SiTraNo/createComponents (line 1295)
            app.UIAxes2.ButtonDownFcn = createCallbackFcn(app, @UIAxes2ButtonDown, true);

Error in SiTraNo (line 1566)
            createComponents(app)

Error in SiTraNoApp/startApp (line 86)
                obj.AppHandle = eval('SiTraNo');

Error in SiTraNoApp (line 48)
            startApp(obj)

Error in appinstall.internal.runapp>execute (line 116)
out = evalin('caller', [script ';']);

Error in appinstall.internal.runapp>runapp13a (line 95)
outobj = execute(fullfile(appinstalldir, [wrapperfile 'App.m']));

Error in appinstall.internal.runapp>preamble18b (line 60)
    appobj = runapp13a(appinstalldir);

Error in appinstall.internal.runapp (line 13)
    out = preamble18b(appinstalldir);

Error in matlab.apputil.run (line 45)
appinstall.internal.runapp(appName, appLocation);
```

All the best,
Anonymous reviewer

**Comment by himynameisfuego** [comment]
Hi! Thanks for contacting me.
I have just quickly looked into it and the problem is indeed the BtnDwnFcn (the callback that is called when you click on a plot). It might be that some versions of Matlab after 2017a (when it was introduced) might handle it differently.

I tried SiTraNo on a 2018a, 2020b and 2021a and it was fine, then I tried it on a 2019b and I got your same error. I removed the callback and the application is running (without the plot interaction) in 2019b.

If you can wait until tomorrow, I will repackage the app as a standalone installer: it should fix the problem.
I will also package a version of the app for you without such a callback, just in case.

-Leonardo

**Comment by himynameisfuego** [comment]
I made an hotfix by simply disabling the faulty callback. It might be tricky to move the time cursor now, as it is possible to click only on the waveform now (a click on an empty part of the plot will produce no effect).

I am working on the standalone versions. I have a Linux one ready, I will try to get a Matlab one asap.

In the meantime @DaFXReviewer: 
[SiTraNo_HotFix_1.0.0.1.zip](https://github.com/himynameisfuego/SiTraNo/files/6351972/SiTraNo_HotFix_1.0.0.1.zip)

Let me know if you encounter any more problems!

**Comment by tommschowar** [comment]
Thanks. I already downloaded it and it works now.
