### ISSUE TITLE
file format

### ISSUE THREAD

**Issue by nimusd** [himynameisfuego/SiTraNo#3]
I read with the utmost interest your description of Sitrano and I am eager to try it, but I don't have Matlab... just the runtime.
Anyway that you can compile the thing in a format that can be run with the runtime?
Thanks,
Nimus

**Comment by himynameisfuego** [comment]
Hi Nimus, thanks for your message. I will have a look at this and try to compile it asap!

**Comment by nimusd** [comment]
Hi Leonardo,
Thank you so much, it will be deeply appreciated.
Nimus

**Comment by nimusd** [comment]
HI Leonardo,
Any chances of the compilation coming before you become too busy with the new academic year?

**Comment by himynameisfuego** [comment]
> HI Leonardo, Any chances of the compilation coming before you become too busy with the new academic year?

Sorry I haven't had any time for this, I am trying to complete my disseration by early October. So I would expect the compiled version to be out by mid October

**Comment by nimusd** [comment]
Yeah!
Best of luck with your dissertation BTW!

**Comment by nimusd** [comment]
Hi Leonardo,
I got the Juce version to get me started but it is not as complete as yours. Are we still on track to get a compiled version sometime soon?

**Comment by himynameisfuego** [comment]
> Hi Leonardo, I got the Juce version to get me started but it is not as complete as yours. Are we still on track to get a compiled version sometime soon?

@nimusd I have produced a compiled version. I will polish a couple of things and add it to the 1.1 release files by the end of today!
